### ISSUE TITLE
Header: logo is blurry

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#15]
Description:
Logo is blurry

screenshot:
![image](https://user-images.githubusercontent.com/75774252/156550347-30279fc4-74b3-42d8-978b-ed6441ad92d0.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Issue persists

![image](https://user-images.githubusercontent.com/75774252/156741741-82fc9b5b-b6e8-40d7-9a63-9b87ed2ba639.png)

**Comment by mrnarvekar** [comment]
Issue fixed. kindly check
![image](https://user-images.githubusercontent.com/89069801/156970137-ecf810f3-87ae-4332-81ea-e42ad51d4cee.png)

**Comment by ShivaniAjency** [comment]
Fixed
