### ISSUE TITLE
MAC OS: Explore articles: UI Issues

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#26]
Description:

1. No space between the article container and the view more button
2. The article container are of different sizes

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/156750381-dea66745-4d95-487e-8af4-30cb5830a6ca.png)

**Comment by mrnarvekar** [comment]
View more button issue is fixed. The container size will be adjusted according to the content and screen resolution as the height is auto. Working properly on MAC OS also
![Screenshot 2022-03-07 at 12 02 48 PM](https://user-images.githubusercontent.com/89069801/156980250-33a947c9-44c7-4bdd-b5fc-5c0a499e4d64.png)
.

**Comment by ShivaniAjency** [comment]
Noted @mrnarvekar . Issue fixed

**Comment by ShivaniAjency** [comment]
No space between the article container and the view more button --> issue persists on MacBook air

The article container are of different sizes--> noted

**Comment by mrnarvekar** [comment]
Kindly test the issue on latest Safari version as the issue is not replicating on Mac OS

**Comment by ShivaniAjency** [comment]
Issue fixed
